# Generated by Django 5.1.3 on 2024-12-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Contact',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
